project:
  type: website
  output-dir: _site

# logo: images/LMLLOGO.png
website:
  title: PS51020A Research Methods & Statistics 2025/6
  repo-url: https://github.com/LittleMonkeyLab/introrm
  site-url: http://introrm.littlemonkeylab.com
  description: Introduction to Research Methods in Psychology at Goldsmiths
  page-navigation: true
  repo-actions: issue
  sidebar:
    title: "Navigation"
    style: docked
    alignment: left
    border: true
    collapse-level: 2
    contents: 
      # - section: "Weeks"
      #   contents: 
      #     - "week**/*.qmd"
      #   exclude: 
      #     - "*-slides.qmd"
      # - text: "---"
      - text: "Course Overview"
        href: index.qmd
      - section: "Demos"
        href: demos.qmd
        contents:
          - text: "WebR"
            href: webr.qmd
          - text: "Web Exercises"
            href: webexercises.qmd
          - text: "Download This"
            href: downloadthis.qmd
      
      

  page-footer:
    center: Copyright 2025, Dr. Gordon Wright
execute:
  freeze: auto
  self-contained: true
format:
  html:
    code-overflow: wrap
    code-line-numbers: false
    code-copy: hover
    comments: 
      hypothesis: true
    theme: default
    mainfont: Atkinson Hyperlegible
    monofont: Fira Code
    toc: true
    license: CC BY-NC-SA
    citation: true
    link-external-newwindow: true
    link-external-icon: false
    css: include/webex.css
    include-after-body: include/webex.js

# Set default options for every webpage that may or may not include webR.
webr: 
  show-startup-message: false
  # Uncomment below as needed
  # show-header-message: false
  # packages: ['ggplot2', 'dplyr']
  # base-url: '' 
  # home-dir: '/home/rstudio'
  # channel-type: 'post-message'
  # service-worker-url: ''

engine: knitr
filters:
  - webr
