name: Publish Quarto site to GitHub Pages

on:
  push:
    branches: [main] # Change if your default branch is not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev \
          libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev \
          libjpeg-dev libpng-dev libtiff5-dev

      - name: Install R package dependencies
        run: Rscript -e "install.packages(c('rmarkdown', 'knitr', 'devtools', 'remotes', 'tinytex')); if (file.exists('DESCRIPTION')) devtools::install_deps(dependencies = TRUE)"

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.32

      - name: Render Quarto site
        run: |
          quarto render

      - name: Upload site as artifact (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: site-build-failed
          path: _site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
