name: Publish Quarto site to GitHub Pages

on:
  push:
    branches: [main] # Change if your default branch is not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Cache renv library
        uses: actions/cache@v4
        with:
          path: renv/library
          key: ${{ runner.os }}-renv-library-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-library-

      - name: Cache renv global cache
        uses: actions/cache@v4
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-cache-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-cache-

      - name: Install R package dependencies with renv
        run: Rscript -e "install.packages('renv'); renv::restore()"

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.32

      - name: Render Quarto site
        run: quarto render

      - name: Upload site as artifact (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: site-build-failed
          path: _site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
