name: Render and Publish

on:
  push:
    branches:
      - main  # changes pushed to this branch will trigger a build.

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::rmarkdown
            any::knitr
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Clean up the _site directory to ensure a fresh build
      - name: Clean up _site directory
        run: |
          rm -rf _site/

      # Retry mechanism to prevent file system issues
      - name: Retry build if rename fails
        run: |
          for i in {1..3}; do
            quarto publish || sleep 10;
          done

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages  # rendered html files will be pushed here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # this secret is always available for github actions
